-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/UnitDelayDUT.vhd
-- Created: 2010-08-16 22:49:49
-- 
-- Generated by MATLAB 7.11 and Simulink HDL Coder 2.0
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Src
-- 
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY UnitDelayTxDUT IS
  PORT( clk         :   IN    std_logic;
        reset       :   IN    std_logic;
        clk_enable  :   IN    std_logic;
        ce_out      :   OUT   std_logic;    
        txdut_in_I  :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        txdut_in_Q  :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        txdut_out_I :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        txdut_out_Q :   OUT   std_logic_vector(15 DOWNTO 0)  -- ufix16
        );
END UnitDelayTxDUT;


ARCHITECTURE rtl OF UnitDelayTxDUT IS

  -- Signals
  SIGNAL enb  : std_logic;

BEGIN

  enb <= clk_enable;

  Unit_Delay3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      txdut_out_I <= ( others => '0');
      txdut_out_Q <= ( others => '0');
    ELSIF clk'EVENT AND clk= '1' THEN
      IF enb = '1' THEN
        txdut_out_I <= txdut_in_I;
        txdut_out_Q <= txdut_in_Q;
      END IF;
    END IF;
  END PROCESS Unit_Delay3_process;

  ce_out <= clk_enable;

END rtl;

