-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\axi_lite_simpledec\axi_lite_simpledec_pcore_dut.vhd
-- Created: 2013-07-31 16:42:14
-- 
-- Generated by MATLAB 8.2 and HDL Coder 3.3
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: axi_lite_simpledec_pcore_dut
-- Source Path: axi_lite_simpledec_pcore/axi_lite_simpledec_pcore_dut
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY axi_lite_simpledec_pcore_dut IS
  PORT( din_I                             :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        din_Q                             :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
        strobe_in                         :   IN    std_logic;  -- ufix1
        wr_decFactor                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        reset                             :   IN    std_logic;  -- ufix1
        clk                               :   IN    std_logic;  -- ufix1
        dout_I                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        dout_Q                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
        strobe_out                        :   OUT   std_logic;  -- ufix1
        rd_decFactor                      :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
        );
END axi_lite_simpledec_pcore_dut;


ARCHITECTURE rtl OF axi_lite_simpledec_pcore_dut IS

  -- Component Declarations
  COMPONENT axi_lite_simpledec
    PORT( din_I                           :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          din_Q                           :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          strobe_in                       :   IN    std_logic;  -- ufix1
          wr_decFactor                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          reset                           :   IN    std_logic;  -- ufix1
          clk                             :   IN    std_logic;  -- ufix1
          dout_I                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          dout_Q                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          strobe_out                      :   OUT   std_logic;  -- ufix1
          rd_decFactor                    :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : axi_lite_simpledec
    USE ENTITY work.axi_lite_simpledec(rtl);

  -- Signals
  SIGNAL strobe_in_sig                    : std_logic;  -- ufix1
  SIGNAL reset_sig                        : std_logic;  -- ufix1
  SIGNAL clk_sig                          : std_logic;  -- ufix1
  SIGNAL dout_I_sig                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL dout_Q_sig                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL strobe_out_sig                   : std_logic;  -- ufix1
  SIGNAL rd_decFactor_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32

BEGIN
  u_axi_lite_simpledec : axi_lite_simpledec
    PORT MAP( din_I => din_I,  -- ufix16
              din_Q => din_Q,  -- ufix16
              strobe_in => strobe_in_sig,  -- ufix1
              wr_decFactor => wr_decFactor,  -- ufix32
              reset => reset_sig,  -- ufix1
              clk => clk_sig,  -- ufix1
              dout_I => dout_I_sig,  -- ufix16
              dout_Q => dout_Q_sig,  -- ufix16
              strobe_out => strobe_out_sig,  -- ufix1
              rd_decFactor => rd_decFactor_sig  -- ufix32
              );

  strobe_in_sig <= strobe_in;

  reset_sig <= reset;

  clk_sig <= clk;

  dout_I <= dout_I_sig;

  dout_Q <= dout_Q_sig;

  strobe_out <= strobe_out_sig;

  rd_decFactor <= rd_decFactor_sig;

END rtl;

