-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\axi_lite_NCO\axi_lite_nco_pcore.vhd
-- Created: 2014-01-21 14:23:43
-- 
-- Generated by MATLAB 8.3 and HDL Coder 3.4
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: -1
-- Target subsystem base rate: -1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: axi_lite_nco_pcore
-- Source Path: axi_lite_nco_pcore
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY axi_lite_nco_pcore IS
  PORT( IPCORE_CLK                        :   IN    std_logic;  -- ufix1
        IPCORE_RESETN                     :   IN    std_logic;  -- ufix1
        clk                               :   IN    std_logic;  -- ufix1
        clk_enable                        :   IN    std_logic;  -- ufix1
        reset                             :   IN    std_logic;  -- ufix1
        dataInVld                         :   IN    std_logic;  -- ufix1
        dataIn                            :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix16 & ufix16
        AXI_Lite_ACLK                     :   IN    std_logic;  -- ufix1
        AXI_Lite_ARESETN                  :   IN    std_logic;  -- ufix1
        AXI_Lite_AWADDR                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI_Lite_AWVALID                  :   IN    std_logic;  -- ufix1
        AXI_Lite_WDATA                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI_Lite_WSTRB                    :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        AXI_Lite_WVALID                   :   IN    std_logic;  -- ufix1
        AXI_Lite_BREADY                   :   IN    std_logic;  -- ufix1
        AXI_Lite_ARADDR                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI_Lite_ARVALID                  :   IN    std_logic;  -- ufix1
        AXI_Lite_RREADY                   :   IN    std_logic;  -- ufix1
        dataOut                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix16 & ufix16
        dataOutVld                        :   OUT   std_logic;  -- ufix1
        AXI_Lite_AWREADY                  :   OUT   std_logic;  -- ufix1
        AXI_Lite_WREADY                   :   OUT   std_logic;  -- ufix1
        AXI_Lite_BRESP                    :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI_Lite_BVALID                   :   OUT   std_logic;  -- ufix1
        AXI_Lite_ARREADY                  :   OUT   std_logic;  -- ufix1
        AXI_Lite_RDATA                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI_Lite_RRESP                    :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI_Lite_RVALID                   :   OUT   std_logic  -- ufix1
        );
END axi_lite_nco_pcore;


ARCHITECTURE rtl OF axi_lite_nco_pcore IS

  -- Component Declarations
  COMPONENT axi_lite_nco_pcore_axi_lite
    PORT( reset_in                        :   IN    std_logic;
          AXI_Lite_ACLK                   :   IN    std_logic;  -- ufix1
          AXI_Lite_ARESETN                :   IN    std_logic;  -- ufix1
          AXI_Lite_AWADDR                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI_Lite_AWVALID                :   IN    std_logic;  -- ufix1
          AXI_Lite_WDATA                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI_Lite_WSTRB                  :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          AXI_Lite_WVALID                 :   IN    std_logic;  -- ufix1
          AXI_Lite_BREADY                 :   IN    std_logic;  -- ufix1
          AXI_Lite_ARADDR                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI_Lite_ARVALID                :   IN    std_logic;  -- ufix1
          AXI_Lite_RREADY                 :   IN    std_logic;  -- ufix1
          read_rd_NCOinc                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          read_rd_debugNCO                :   IN    std_logic;  -- ufix1
          AXI_Lite_AWREADY                :   OUT   std_logic;  -- ufix1
          AXI_Lite_WREADY                 :   OUT   std_logic;  -- ufix1
          AXI_Lite_BRESP                  :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI_Lite_BVALID                 :   OUT   std_logic;  -- ufix1
          AXI_Lite_ARREADY                :   OUT   std_logic;  -- ufix1
          AXI_Lite_RDATA                  :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI_Lite_RRESP                  :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI_Lite_RVALID                 :   OUT   std_logic;  -- ufix1
          write_wr_NCOinc                 :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_wr_debugNCO               :   OUT   std_logic;  -- ufix1
          reset_internal                  :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT axi_lite_nco_pcore_dut
    PORT( wr_NCOinc                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          clk                             :   IN    std_logic;  -- ufix1
          clk_enable                      :   IN    std_logic;  -- ufix1
          reset                           :   IN    std_logic;  -- ufix1
          dataInVld                       :   IN    std_logic;  -- ufix1
          wr_debugNCO                     :   IN    std_logic;  -- ufix1
          dataIn_I                        :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          dataIn_Q                        :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          rd_NCOinc                       :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dataOut_I                       :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          dataOut_Q                       :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          dataOutVld                      :   OUT   std_logic;  -- ufix1
          rd_debugNCO                     :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : axi_lite_nco_pcore_axi_lite
    USE ENTITY work.axi_lite_nco_pcore_axi_lite(rtl);

  FOR ALL : axi_lite_nco_pcore_dut
    USE ENTITY work.axi_lite_nco_pcore_dut(rtl);

  -- Signals
  SIGNAL reset_in                         : std_logic;
  SIGNAL reset_cm                         : std_logic;  -- ufix1
  SIGNAL reset_internal                   : std_logic;  -- ufix1
  SIGNAL rd_NCOinc_sig                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL rd_debugNCO_sig                  : std_logic;  -- ufix1
  SIGNAL AXI_Lite_BRESP_tmp               : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL AXI_Lite_RDATA_tmp               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL AXI_Lite_RRESP_tmp               : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL wr_NCOinc_sig                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL wr_debugNCO_sig                  : std_logic;  -- ufix1
  SIGNAL dataOut_I_sig                    : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL dataOut_Q_sig                    : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL dataOutVld_sig                   : std_logic;  -- ufix1
  SIGNAL dataIn_I                         : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL dataIn_Q                         : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_axi_lite_nco_pcore_axi_lite_inst : axi_lite_nco_pcore_axi_lite
    PORT MAP( reset_in => reset_in,
              AXI_Lite_ACLK => AXI_Lite_ACLK,  -- ufix1
              AXI_Lite_ARESETN => AXI_Lite_ARESETN,  -- ufix1
              AXI_Lite_AWADDR => AXI_Lite_AWADDR,  -- ufix32
              AXI_Lite_AWVALID => AXI_Lite_AWVALID,  -- ufix1
              AXI_Lite_WDATA => AXI_Lite_WDATA,  -- ufix32
              AXI_Lite_WSTRB => AXI_Lite_WSTRB,  -- ufix4
              AXI_Lite_WVALID => AXI_Lite_WVALID,  -- ufix1
              AXI_Lite_BREADY => AXI_Lite_BREADY,  -- ufix1
              AXI_Lite_ARADDR => AXI_Lite_ARADDR,  -- ufix32
              AXI_Lite_ARVALID => AXI_Lite_ARVALID,  -- ufix1
              AXI_Lite_RREADY => AXI_Lite_RREADY,  -- ufix1
              read_rd_NCOinc => rd_NCOinc_sig,  -- ufix32
              read_rd_debugNCO => rd_debugNCO_sig,  -- ufix1
              AXI_Lite_AWREADY => AXI_Lite_AWREADY,  -- ufix1
              AXI_Lite_WREADY => AXI_Lite_WREADY,  -- ufix1
              AXI_Lite_BRESP => AXI_Lite_BRESP_tmp,  -- ufix2
              AXI_Lite_BVALID => AXI_Lite_BVALID,  -- ufix1
              AXI_Lite_ARREADY => AXI_Lite_ARREADY,  -- ufix1
              AXI_Lite_RDATA => AXI_Lite_RDATA_tmp,  -- ufix32
              AXI_Lite_RRESP => AXI_Lite_RRESP_tmp,  -- ufix2
              AXI_Lite_RVALID => AXI_Lite_RVALID,  -- ufix1
              write_wr_NCOinc => wr_NCOinc_sig,  -- ufix32
              write_wr_debugNCO => wr_debugNCO_sig,  -- ufix1
              reset_internal => reset_internal  -- ufix1
              );

  u_axi_lite_nco_pcore_dut_inst : axi_lite_nco_pcore_dut
    PORT MAP( wr_NCOinc => wr_NCOinc_sig,  -- ufix32
              clk => clk,  -- ufix1
              clk_enable => clk_enable,  -- ufix1
              reset => reset,  -- ufix1
              dataInVld => dataInVld,  -- ufix1
              wr_debugNCO => wr_debugNCO_sig,  -- ufix1
              dataIn_I => dataIn_I,  -- ufix16
              dataIn_Q => dataIn_Q,  -- ufix16
              rd_NCOinc => rd_NCOinc_sig,  -- ufix32
              dataOut_I => dataOut_I_sig,  -- ufix16
              dataOut_Q => dataOut_Q_sig,  -- ufix16
              dataOutVld => dataOutVld_sig,  -- ufix1
              rd_debugNCO => rd_debugNCO_sig  -- ufix1
              );

  reset_cm <=  NOT IPCORE_RESETN;

  reset_in <= reset_cm OR reset_internal;

  dataOutVld <= dataOutVld_sig;

  dataOut <= dataOut_Q_sig & dataOut_I_sig;

  AXI_Lite_BRESP <= AXI_Lite_BRESP_tmp;

  AXI_Lite_RDATA <= AXI_Lite_RDATA_tmp;

  AXI_Lite_RRESP <= AXI_Lite_RRESP_tmp;
  
  dataIn_I <= dataIn(15 downto 0);
  dataIn_Q <= dataIn(31 downto 16);

END rtl;

