function [driverHandle, errStat, errId, errStr] = sdr_setupImpl( ...
        creationArgsSize, creationArgs, ...
        nonTunablePropsSize, nonTunableProps, ...
        tunablePropsSize, tunableProps)
%#codegen

%   Copyright 2014 The MathWorks, Inc.

[driverHandle, errStat, errId, errStr] = sdr_mapiPrivate('setupImpl', ...
        creationArgsSize, creationArgs, ...
        nonTunablePropsSize, nonTunableProps, ...
        tunablePropsSize, tunableProps);

end
