-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\axi_lite_sdrsrc\axi_lite_sdrsrc_pcore.vhd
-- Created: 2014-02-27 10:13:04
-- 
-- Generated by MATLAB 8.3 and HDL Coder 3.4
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: -1
-- Target subsystem base rate: -1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: axi_lite_sdrsrc_pcore
-- Source Path: axi_lite_sdrsrc_pcore
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY axi_lite_sdrsrc_pcore IS
  PORT( IPCORE_CLK                        :   IN    std_logic;  -- ufix1
        IPCORE_RESETN                     :   IN    std_logic;  -- ufix1
        clk                               :   IN    std_logic;  -- ufix1
        reset                             :   IN    std_logic;  -- ufix1
        stream_en                         :   IN    std_logic;  -- ufix1
        RFIn                              :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix16 & ufix16
        RFIn_strb                         :   IN    std_logic;  -- ufix1
        loop_in                           :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix16 & ufix16
        loop_vld                          :   IN    std_logic;  -- ufix1
        AXI_Lite_ACLK                     :   IN    std_logic;  -- ufix1
        AXI_Lite_ARESETN                  :   IN    std_logic;  -- ufix1
        AXI_Lite_AWADDR                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI_Lite_AWVALID                  :   IN    std_logic;  -- ufix1
        AXI_Lite_WDATA                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI_Lite_WSTRB                    :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        AXI_Lite_WVALID                   :   IN    std_logic;  -- ufix1
        AXI_Lite_BREADY                   :   IN    std_logic;  -- ufix1
        AXI_Lite_ARADDR                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI_Lite_ARVALID                  :   IN    std_logic;  -- ufix1
        AXI_Lite_RREADY                   :   IN    std_logic;  -- ufix1
        src_strobe                        :   OUT   std_logic;  -- ufix1
        src_out                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix16 & ufix16
        AXI_Lite_AWREADY                  :   OUT   std_logic;  -- ufix1
        AXI_Lite_WREADY                   :   OUT   std_logic;  -- ufix1
        AXI_Lite_BRESP                    :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI_Lite_BVALID                   :   OUT   std_logic;  -- ufix1
        AXI_Lite_ARREADY                  :   OUT   std_logic;  -- ufix1
        AXI_Lite_RDATA                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI_Lite_RRESP                    :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI_Lite_RVALID                   :   OUT   std_logic  -- ufix1
        );
END axi_lite_sdrsrc_pcore;


ARCHITECTURE rtl OF axi_lite_sdrsrc_pcore IS

  -- Component Declarations
  COMPONENT axi_lite_sdrsrc_pcore_axi_lite
    PORT( reset_in                        :   IN    std_logic;
          AXI_Lite_ACLK                   :   IN    std_logic;  -- ufix1
          AXI_Lite_ARESETN                :   IN    std_logic;  -- ufix1
          AXI_Lite_AWADDR                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI_Lite_AWVALID                :   IN    std_logic;  -- ufix1
          AXI_Lite_WDATA                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI_Lite_WSTRB                  :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          AXI_Lite_WVALID                 :   IN    std_logic;  -- ufix1
          AXI_Lite_BREADY                 :   IN    std_logic;  -- ufix1
          AXI_Lite_ARADDR                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI_Lite_ARVALID                :   IN    std_logic;  -- ufix1
          AXI_Lite_RREADY                 :   IN    std_logic;  -- ufix1
          read_rd_src_sel                 :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
          read_rd_src_amp                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          read_rd_src_freq                :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI_Lite_AWREADY                :   OUT   std_logic;  -- ufix1
          AXI_Lite_WREADY                 :   OUT   std_logic;  -- ufix1
          AXI_Lite_BRESP                  :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI_Lite_BVALID                 :   OUT   std_logic;  -- ufix1
          AXI_Lite_ARREADY                :   OUT   std_logic;  -- ufix1
          AXI_Lite_RDATA                  :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI_Lite_RRESP                  :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI_Lite_RVALID                 :   OUT   std_logic;  -- ufix1
          write_wr_src_sel                :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          write_wr_src_amp                :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          write_wr_src_freq               :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          reset_internal                  :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT axi_lite_sdrsrc_pcore_dut
    PORT( clk                             :   IN    std_logic;  -- ufix1
          reset                           :   IN    std_logic;  -- ufix1
          stream_en                       :   IN    std_logic;  -- ufix1
          wr_src_sel                      :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
          wr_src_amp                      :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          RFIn_I                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          RFIn_Q                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          RFIn_strb                       :   IN    std_logic;  -- ufix1
          loop_I                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          loop_Q                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          loop_vld                        :   IN    std_logic;  -- ufix1
          wr_src_freq                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          src_strobe                      :   OUT   std_logic;  -- ufix1
          src_I                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          src_Q                           :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          rd_src_sel                      :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          rd_src_amp                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          rd_src_freq                     :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : axi_lite_sdrsrc_pcore_axi_lite
    USE ENTITY work.axi_lite_sdrsrc_pcore_axi_lite(rtl);

  FOR ALL : axi_lite_sdrsrc_pcore_dut
    USE ENTITY work.axi_lite_sdrsrc_pcore_dut(rtl);

  -- Signals
  SIGNAL reset_in                         : std_logic;
  SIGNAL reset_cm                         : std_logic;  -- ufix1
  SIGNAL reset_internal                   : std_logic;  -- ufix1
  SIGNAL rd_src_sel_sig                   : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL rd_src_amp_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL rd_src_freq_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL AXI_Lite_BRESP_tmp               : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL AXI_Lite_RDATA_tmp               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL AXI_Lite_RRESP_tmp               : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL wr_src_sel_sig                   : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL wr_src_amp_sig                   : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL wr_src_freq_sig                  : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL src_strobe_sig                   : std_logic;  -- ufix1
  SIGNAL src_I_sig                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL src_Q_sig                        : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL RFIn_I                           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL RFIn_Q                           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL loop_I                           : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL loop_Q                           : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_axi_lite_sdrsrc_pcore_axi_lite_inst : axi_lite_sdrsrc_pcore_axi_lite
    PORT MAP( reset_in => reset_in,
              AXI_Lite_ACLK => AXI_Lite_ACLK,  -- ufix1
              AXI_Lite_ARESETN => AXI_Lite_ARESETN,  -- ufix1
              AXI_Lite_AWADDR => AXI_Lite_AWADDR,  -- ufix32
              AXI_Lite_AWVALID => AXI_Lite_AWVALID,  -- ufix1
              AXI_Lite_WDATA => AXI_Lite_WDATA,  -- ufix32
              AXI_Lite_WSTRB => AXI_Lite_WSTRB,  -- ufix4
              AXI_Lite_WVALID => AXI_Lite_WVALID,  -- ufix1
              AXI_Lite_BREADY => AXI_Lite_BREADY,  -- ufix1
              AXI_Lite_ARADDR => AXI_Lite_ARADDR,  -- ufix32
              AXI_Lite_ARVALID => AXI_Lite_ARVALID,  -- ufix1
              AXI_Lite_RREADY => AXI_Lite_RREADY,  -- ufix1
              read_rd_src_sel => rd_src_sel_sig,  -- ufix2
              read_rd_src_amp => rd_src_amp_sig,  -- ufix32
              read_rd_src_freq => rd_src_freq_sig,  -- ufix32
              AXI_Lite_AWREADY => AXI_Lite_AWREADY,  -- ufix1
              AXI_Lite_WREADY => AXI_Lite_WREADY,  -- ufix1
              AXI_Lite_BRESP => AXI_Lite_BRESP_tmp,  -- ufix2
              AXI_Lite_BVALID => AXI_Lite_BVALID,  -- ufix1
              AXI_Lite_ARREADY => AXI_Lite_ARREADY,  -- ufix1
              AXI_Lite_RDATA => AXI_Lite_RDATA_tmp,  -- ufix32
              AXI_Lite_RRESP => AXI_Lite_RRESP_tmp,  -- ufix2
              AXI_Lite_RVALID => AXI_Lite_RVALID,  -- ufix1
              write_wr_src_sel => wr_src_sel_sig,  -- ufix2
              write_wr_src_amp => wr_src_amp_sig,  -- ufix32
              write_wr_src_freq => wr_src_freq_sig,  -- ufix32
              reset_internal => reset_internal  -- ufix1
              );

  u_axi_lite_sdrsrc_pcore_dut_inst : axi_lite_sdrsrc_pcore_dut
    PORT MAP( clk => clk,  -- ufix1
              reset => reset,  -- ufix1
              stream_en => stream_en,  -- ufix1
              wr_src_sel => wr_src_sel_sig,  -- ufix2
              wr_src_amp => wr_src_amp_sig,  -- ufix32
              RFIn_I => RFIn_I,  -- ufix16
              RFIn_Q => RFIn_Q,  -- ufix16
              RFIn_strb => RFIn_strb,  -- ufix1
              loop_I => loop_I,  -- ufix16
              loop_Q => loop_Q,  -- ufix16
              loop_vld => loop_vld,  -- ufix1
              wr_src_freq => wr_src_freq_sig,  -- ufix32
              src_strobe => src_strobe_sig,  -- ufix1
              src_I => src_I_sig,  -- ufix16
              src_Q => src_Q_sig,  -- ufix16
              rd_src_sel => rd_src_sel_sig,  -- ufix2
              rd_src_amp => rd_src_amp_sig,  -- ufix32
              rd_src_freq => rd_src_freq_sig  -- ufix32
              );

  reset_cm <=  NOT IPCORE_RESETN;

  reset_in <= reset_cm OR reset_internal;

  src_strobe <= src_strobe_sig;
  src_out    <= src_Q_sig & src_I_sig;

  AXI_Lite_BRESP <= AXI_Lite_BRESP_tmp;

  AXI_Lite_RDATA <= AXI_Lite_RDATA_tmp;

  AXI_Lite_RRESP <= AXI_Lite_RRESP_tmp;
  
  RFIn_I <= RFIn(15 downto 0);
  RFIn_Q <= RFIn(31 downto 16);
  
  loop_I <= loop_in(15 downto 0);
  loop_Q <= loop_in(31 downto 16);  

END rtl;

