-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc_fir_without_mode\msdrfdcblocker\SDRDCBlockerTop_pkg.vhd
-- Created: 2013-10-24 17:20:28
-- 
-- Generated by MATLAB 8.3 and HDL Coder 3.4
-- 
-- -------------------------------------------------------------


LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

PACKAGE SDRDCBlockerTop_pkg IS
  TYPE vector_of_signed17 IS ARRAY (NATURAL RANGE <>) OF signed(16 DOWNTO 0);
  TYPE vector_of_signed18 IS ARRAY (NATURAL RANGE <>) OF signed(17 DOWNTO 0);
END SDRDCBlockerTop_pkg;

