-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\axi_lite_simpleint\axi_lite_simpleint_pcore_addr_decoder.vhd
-- Created: 2014-03-09 13:14:47
-- 
-- Generated by MATLAB 8.3 and HDL Coder 3.4
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: axi_lite_simpleint_pcore_addr_decoder
-- Source Path: axi_lite_simpleint_pcore/axi_lite_simpleint_pcore_axi_lite/axi_lite_simpleint_pcore_addr_decoder
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY axi_lite_simpleint_pcore_addr_decoder IS
  PORT( clk_in                            :   IN    std_logic;
        reset_in                          :   IN    std_logic;
        data_write                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        addr_sel                          :   IN    std_logic_vector(13 DOWNTO 0);  -- ufix14
        wr_enb                            :   IN    std_logic;  -- ufix1
        rd_enb                            :   IN    std_logic;  -- ufix1
        read_rd_intFactor                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        data_read                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        write_wr_intFactor                :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
        );
END axi_lite_simpleint_pcore_addr_decoder;


ARCHITECTURE rtl OF axi_lite_simpleint_pcore_addr_decoder IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL addr_sel_unsigned                : unsigned(13 DOWNTO 0);  -- ufix14
  SIGNAL decode_sel_rd_intFactor          : std_logic;  -- ufix1
  SIGNAL const_z                          : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL read_rd_intFactor_unsigned       : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL const_1                          : std_logic;  -- ufix1
  SIGNAL read_reg_rd_intFactor            : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_rd_rd_intFactor           : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL data_write_unsigned              : unsigned(31 DOWNTO 0);  -- ufix32
  SIGNAL decode_sel_wr_intFactor          : std_logic;  -- ufix1
  SIGNAL reg_enb_wr_intFactor             : std_logic;  -- ufix1
  SIGNAL write_reg_wr_intFactor           : unsigned(31 DOWNTO 0);  -- ufix32

BEGIN
  addr_sel_unsigned <= unsigned(addr_sel);

  
  decode_sel_rd_intFactor <= '1' WHEN addr_sel_unsigned = to_unsigned(2#00000001000001#, 14) ELSE
      '0';

  const_z <= (OTHERS => 'Z');


  read_rd_intFactor_unsigned <= unsigned(read_rd_intFactor);

  const_1 <= '1';

  enb <= const_1;

  reg_rd_intFactor_process : PROCESS (clk_in, reset_in)
  BEGIN
    IF reset_in = '1' THEN
      read_reg_rd_intFactor <= to_unsigned(0, 32);
    ELSIF clk_in'EVENT AND clk_in = '1' THEN
      IF enb = '1' THEN
        read_reg_rd_intFactor <= read_rd_intFactor_unsigned;
      END IF;
    END IF;
  END PROCESS reg_rd_intFactor_process;


  
  decode_rd_rd_intFactor <= const_z WHEN decode_sel_rd_intFactor = '0' ELSE
      read_reg_rd_intFactor;

  data_read <= std_logic_vector(decode_rd_rd_intFactor);

  data_write_unsigned <= unsigned(data_write);

  
  decode_sel_wr_intFactor <= '1' WHEN addr_sel_unsigned = to_unsigned(2#00000001000000#, 14) ELSE
      '0';

  reg_enb_wr_intFactor <= decode_sel_wr_intFactor AND wr_enb;

  reg_wr_intFactor_process : PROCESS (clk_in, reset_in)
  BEGIN
    IF reset_in = '1' THEN
      write_reg_wr_intFactor <= to_unsigned(0, 32);
    ELSIF clk_in'EVENT AND clk_in = '1' THEN
      IF enb = '1' AND reg_enb_wr_intFactor = '1' THEN
        write_reg_wr_intFactor <= data_write_unsigned;
      END IF;
    END IF;
  END PROCESS reg_wr_intFactor_process;


  write_wr_intFactor <= std_logic_vector(write_reg_wr_intFactor);

END rtl;

