-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\axi_lite_simpleint\axi_lite_simpleint_pcore.vhd
-- Created: 2014-03-09 13:14:47
-- 
-- Generated by MATLAB 8.3 and HDL Coder 3.4
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: -1
-- Target subsystem base rate: -1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: axi_lite_simpleint_pcore
-- Source Path: axi_lite_simpleint_pcore
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY axi_lite_simpleint_pcore IS
  PORT( IPCORE_CLK                        :   IN    std_logic;  -- ufix1
        IPCORE_RESETN                     :   IN    std_logic;  -- ufix1
        din                               :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix16 & ufix16
        clk                               :   IN    std_logic;  -- ufix1
        din_vld                           :   IN    std_logic;  -- ufix1
        reset                             :   IN    std_logic;  -- ufix1
        AXI_Lite_ACLK                     :   IN    std_logic;  -- ufix1
        AXI_Lite_ARESETN                  :   IN    std_logic;  -- ufix1
        AXI_Lite_AWADDR                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI_Lite_AWVALID                  :   IN    std_logic;  -- ufix1
        AXI_Lite_WDATA                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI_Lite_WSTRB                    :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
        AXI_Lite_WVALID                   :   IN    std_logic;  -- ufix1
        AXI_Lite_BREADY                   :   IN    std_logic;  -- ufix1
        AXI_Lite_ARADDR                   :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI_Lite_ARVALID                  :   IN    std_logic;  -- ufix1
        AXI_Lite_RREADY                   :   IN    std_logic;  -- ufix1
        dout                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix16 & ufix16
        dout_vld                          :   OUT   std_logic;  -- ufix1
        intFactor                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI_Lite_AWREADY                  :   OUT   std_logic;  -- ufix1
        AXI_Lite_WREADY                   :   OUT   std_logic;  -- ufix1
        AXI_Lite_BRESP                    :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI_Lite_BVALID                   :   OUT   std_logic;  -- ufix1
        AXI_Lite_ARREADY                  :   OUT   std_logic;  -- ufix1
        AXI_Lite_RDATA                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
        AXI_Lite_RRESP                    :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
        AXI_Lite_RVALID                   :   OUT   std_logic  -- ufix1
        );
END axi_lite_simpleint_pcore;


ARCHITECTURE rtl OF axi_lite_simpleint_pcore IS

  -- Component Declarations
  COMPONENT axi_lite_simpleint_pcore_axi_lite
    PORT( reset_in                        :   IN    std_logic;
          AXI_Lite_ACLK                   :   IN    std_logic;  -- ufix1
          AXI_Lite_ARESETN                :   IN    std_logic;  -- ufix1
          AXI_Lite_AWADDR                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI_Lite_AWVALID                :   IN    std_logic;  -- ufix1
          AXI_Lite_WDATA                  :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI_Lite_WSTRB                  :   IN    std_logic_vector(3 DOWNTO 0);  -- ufix4
          AXI_Lite_WVALID                 :   IN    std_logic;  -- ufix1
          AXI_Lite_BREADY                 :   IN    std_logic;  -- ufix1
          AXI_Lite_ARADDR                 :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI_Lite_ARVALID                :   IN    std_logic;  -- ufix1
          AXI_Lite_RREADY                 :   IN    std_logic;  -- ufix1
          read_rd_intFactor               :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI_Lite_AWREADY                :   OUT   std_logic;  -- ufix1
          AXI_Lite_WREADY                 :   OUT   std_logic;  -- ufix1
          AXI_Lite_BRESP                  :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI_Lite_BVALID                 :   OUT   std_logic;  -- ufix1
          AXI_Lite_ARREADY                :   OUT   std_logic;  -- ufix1
          AXI_Lite_RDATA                  :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          AXI_Lite_RRESP                  :   OUT   std_logic_vector(1 DOWNTO 0);  -- ufix2
          AXI_Lite_RVALID                 :   OUT   std_logic;  -- ufix1
          write_wr_intFactor              :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          reset_internal                  :   OUT   std_logic  -- ufix1
          );
  END COMPONENT;

  COMPONENT axi_lite_simpleint_pcore_dut
    PORT( wr_intFactor                    :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32
          din_I                           :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          din_Q                           :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16
          clk                             :   IN    std_logic;  -- ufix1
          din_vld                         :   IN    std_logic;  -- ufix1
          reset                           :   IN    std_logic;  -- ufix1
          rd_intFactor                    :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32
          dout_I                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          dout_Q                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- ufix16
          dout_vld                        :   OUT   std_logic;  -- ufix1
          intFactor                       :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : axi_lite_simpleint_pcore_axi_lite
    USE ENTITY work.axi_lite_simpleint_pcore_axi_lite(rtl);

  FOR ALL : axi_lite_simpleint_pcore_dut
    USE ENTITY work.axi_lite_simpleint_pcore_dut(rtl);

  -- Signals
  SIGNAL reset_in                         : std_logic;
  SIGNAL reset_cm                         : std_logic;  -- ufix1
  SIGNAL reset_internal                   : std_logic;  -- ufix1
  SIGNAL rd_intFactor_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL AXI_Lite_BRESP_tmp               : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL AXI_Lite_RDATA_tmp               : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL AXI_Lite_RRESP_tmp               : std_logic_vector(1 DOWNTO 0);  -- ufix2
  SIGNAL wr_intFactor_sig                 : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL dout_I_sig                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL dout_Q_sig                       : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL dout_vld_sig                     : std_logic;  -- ufix1
  SIGNAL intFactor_sig                    : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL din_I                            : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL din_Q                            : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_axi_lite_simpleint_pcore_axi_lite_inst : axi_lite_simpleint_pcore_axi_lite
    PORT MAP( reset_in => reset_in,
              AXI_Lite_ACLK => AXI_Lite_ACLK,  -- ufix1
              AXI_Lite_ARESETN => AXI_Lite_ARESETN,  -- ufix1
              AXI_Lite_AWADDR => AXI_Lite_AWADDR,  -- ufix32
              AXI_Lite_AWVALID => AXI_Lite_AWVALID,  -- ufix1
              AXI_Lite_WDATA => AXI_Lite_WDATA,  -- ufix32
              AXI_Lite_WSTRB => AXI_Lite_WSTRB,  -- ufix4
              AXI_Lite_WVALID => AXI_Lite_WVALID,  -- ufix1
              AXI_Lite_BREADY => AXI_Lite_BREADY,  -- ufix1
              AXI_Lite_ARADDR => AXI_Lite_ARADDR,  -- ufix32
              AXI_Lite_ARVALID => AXI_Lite_ARVALID,  -- ufix1
              AXI_Lite_RREADY => AXI_Lite_RREADY,  -- ufix1
              read_rd_intFactor => rd_intFactor_sig,  -- ufix32
              AXI_Lite_AWREADY => AXI_Lite_AWREADY,  -- ufix1
              AXI_Lite_WREADY => AXI_Lite_WREADY,  -- ufix1
              AXI_Lite_BRESP => AXI_Lite_BRESP_tmp,  -- ufix2
              AXI_Lite_BVALID => AXI_Lite_BVALID,  -- ufix1
              AXI_Lite_ARREADY => AXI_Lite_ARREADY,  -- ufix1
              AXI_Lite_RDATA => AXI_Lite_RDATA_tmp,  -- ufix32
              AXI_Lite_RRESP => AXI_Lite_RRESP_tmp,  -- ufix2
              AXI_Lite_RVALID => AXI_Lite_RVALID,  -- ufix1
              write_wr_intFactor => wr_intFactor_sig,  -- ufix32
              reset_internal => reset_internal  -- ufix1
              );

  u_axi_lite_simpleint_pcore_dut_inst : axi_lite_simpleint_pcore_dut
    PORT MAP( wr_intFactor => wr_intFactor_sig,  -- ufix32
              din_I => din_I,  -- ufix16
              din_Q => din_Q,  -- ufix16
              clk => clk,  -- ufix1
              din_vld => din_vld,  -- ufix1
              reset => reset,  -- ufix1
              rd_intFactor => rd_intFactor_sig,  -- ufix32
              dout_I => dout_I_sig,  -- ufix16
              dout_Q => dout_Q_sig,  -- ufix16
              dout_vld => dout_vld_sig,  -- ufix1
              intFactor => intFactor_sig  -- ufix32
              );

  reset_cm <=  NOT IPCORE_RESETN;

  reset_in <= reset_cm OR reset_internal;

  dout_vld <= dout_vld_sig;

  dout <= dout_Q_sig & dout_I_sig;

  intFactor <= intFactor_sig;

  AXI_Lite_BRESP <= AXI_Lite_BRESP_tmp;

  AXI_Lite_RDATA <= AXI_Lite_RDATA_tmp;

  AXI_Lite_RRESP <= AXI_Lite_RRESP_tmp;
  
  din_I <= din(15 downto 0);
  din_Q <= din(31 downto 16);

END rtl;

