-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\axi_lite_simpleint\axi_lite_simpleint.vhd
-- Created: 2013-09-20 17:34:13
-- 
-- Generated by MATLAB 8.2 and HDL Coder 3.3
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0.2
-- Target subsystem base rate: 0.2
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: axi_lite_simpleint
-- Source Path: axi_lite_simpleint
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY axi_lite_simpleint IS
  PORT( wr_intFactor    : IN    std_logic_vector(31 DOWNTO 0);  -- uint32
        din_I           : IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        din_Q           : IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        clk             : IN    std_logic;  -- ufix1
        din_vld         : IN    std_logic;  -- ufix1
        reset           : IN    std_logic;  -- ufix1
        rd_intFactor    : OUT   std_logic_vector(31 DOWNTO 0);  -- uint32
        intFactor       : OUT   std_logic_vector(31 DOWNTO 0);  -- exposed value of intfactor register for use in axis demapper
        dout_I          : OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        dout_Q          : OUT   std_logic_vector(15 DOWNTO 0);  -- uint16
        dout_vld        : OUT   std_logic  -- ufix1
        );
END axi_lite_simpleint;


ARCHITECTURE rtl OF axi_lite_simpleint IS

  -- Component Declarations
  COMPONENT SDRSimpleInt is
  port (
        clk   : in std_logic;
        reset : in std_logic;
        
        din_I     : in std_logic_vector(15 downto 0);
        din_Q     : in std_logic_vector(15 downto 0);
        din_vld   : in std_logic;
        intFactor : in std_logic_vector(31 downto 0);
    
        dout_I    : out std_logic_vector(15 downto 0);
        dout_Q    : out std_logic_vector(15 downto 0);
        dout_vld  : out std_logic
    );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : SDRSimpleInt
    USE ENTITY work.SDRSimpleInt(rtl);

  -- Signals

BEGIN
  u_SDRSimpleInt : SDRSimpleInt
    PORT MAP( intFactor => wr_intFactor,  -- uint32
              din_I => din_I,  -- uint16
              din_Q => din_Q,  -- uint16
              clk => clk,  -- ufix1
              din_vld => din_vld,  -- ufix1
              reset => reset,  -- ufix1
              dout_I => dout_I,  -- uint16
              dout_Q => dout_Q,  -- uint16
              dout_vld => dout_vld-- ufix1
              );

  rd_intFactor <= wr_intFactor;
  intFactor <= wr_intFactor;

END rtl;

